print "hello, world!"
print "hi, this is my first python program"
print "I heard python is the most nature language so far"
print "many scientists used python as their daily tool to program"
print "From my point of view, it is just like speaking English"
